// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4mW57x-fdzyI2p6whibcRKV1lIK4NKVE',
    appId: '1:474568791761:web:936f2a05b17acdcfbf17f0',
    messagingSenderId: '474568791761',
    projectId: 'bylaive-aeeeb',
    authDomain: 'bylaive-aeeeb.firebaseapp.com',
    storageBucket: 'bylaive-aeeeb.appspot.com',
    measurementId: 'G-XX76SL26WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6X6MkTI9QtvyFov9UwiWNG9JWqPOknok',
    appId: '1:474568791761:android:53bc1bd7309a063cbf17f0',
    messagingSenderId: '474568791761',
    projectId: 'bylaive-aeeeb',
    storageBucket: 'bylaive-aeeeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCweJg_DikMrUy9LZPRzYqCZPP1LicJKqU',
    appId: '1:474568791761:ios:75d89f7371983d50bf17f0',
    messagingSenderId: '474568791761',
    projectId: 'bylaive-aeeeb',
    storageBucket: 'bylaive-aeeeb.appspot.com',
    androidClientId: '474568791761-84c5qf9ks5qkr1bdf88hq43a5h6ctki4.apps.googleusercontent.com',
    iosClientId: '474568791761-46o1f51htirrnqnpnqkhpie5k3umas3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.bylaive',
  );
}
